Repository aws-controllers-k8s/opensearchservice-controller, pull requests merged in 2021-12, with the labels that each got.

#8 replace plaintext password with secret ref
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/opensearchservice.services.k8s.aws_domains.yaml
  config/rbac/cluster-role-controller.yaml
  generator.yaml
  helm/crds/opensearchservice.services.k8s.aws_domains.yaml
  helm/templates/cluster-role-controller.yaml
  pkg/resource/domain/sdk.go
  pkg/resource/registry.go
  test/e2e/bootstrap_resources.py
  test/e2e/resources/domain_es7.9.yaml
  test/e2e/resources/domain_es_xdym_multi_az7.9.yaml
  test/e2e/resources/domain_es_xdym_multi_az_vpc7.9.yaml
  test/e2e/secret.py
  test/e2e/service_bootstrap.py
  test/e2e/tests/test_domain.py
Labels: lgtm, approved

#9 release artifacts for v0.0.3
  helm/Chart.yaml
  helm/templates/deployment.yaml
  helm/values.yaml
Labels: approved

#10 adding in missing olmconfig file
  olm/olmconfig.yaml
Labels: lgtm, approved, ok-to-test
